{{- if and .Values.enabled (eq .Values.kind "ConfigMap")}}
apiVersion: v1
kind: {{ .Values.kind }}
metadata:
  name: {{ include "common.name" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
{{-   include "common.labels" . | nindent 4 }}
{{-   with .Values.metadata.labels }}
{{-     toYaml . | nindent 4 }}
{{-   end }}
{{-   with .Values.metadata.annotations }}
  annotations:
{{-     toYaml . | nindent 4 }}
{{-   end }}
data:
{{-   $mergedData := mergeOverwrite (dict) .Values.extraData .Values.data }}
{{-   range $key, $val := $mergedData }}
{{      $key | indent 2}}: {{ $val | quote }}
{{-   end }}
{{- end }}
